language: generic

services:
  - docker

os:
  - linux

env:
  global:
    - IMAGE_FOLDER=robotology-tdd
    - DOCKER_IMAGE_NAME="robotology-tdd"

stages:
  - robotology-tdd

script:
  - cd $TRAVIS_BUILD_DIR/$IMAGE_FOLDER
  - >-
    docker build --rm \
      --build-arg BASE_IMAGE=$DOCKER_BASE_IMAGE \
      --build-arg GAZEBO_VER=$GAZEBO_VER \
      --build-arg BRANCH=$BRANCH \
      --build-arg CMAKE_GENERATOR="$CMAKE_GENERATOR" \
      --build-arg CMAKE_EXTRA_OPTIONS=$CMAKE_EXTRA_OPTIONS \
      -t robotology/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG \
      .

after_success:
  - if ! [[ "$TRAVIS_REPO_SLUG" = "robotology-playground/docker_images" && "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then travis_terminate 0 ; fi
  - docker login --username=$DOCKERHUB_USERNAME --password=$DOCKERHUB_PASSWORD
  - docker push robotology/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  - >-
    if [ "$IS_LATEST" = "true" ] ; then
      docker tag robotology/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG robotology/$DOCKER_IMAGE_NAME:latest
      docker push robotology/$DOCKER_IMAGE_NAME:latest
    fi

jobs:
  include:
    # Disable test stage
    - stage: test
      if: env(DUMMYVAR) is present
    # ==============
    # ROBOTOLOGY-TDD
    # ==============
    #
    # ------
    # MASTER
    # ------
    - &robotologytddtemplate
      stage: robotology-tdd
      env:
        - DOCKER_BASE_IMAGE="ubuntu:xenial"
        - DOCKER_IMAGE_TAG="gazebo8master"
        - GAZEBO_VER=8
        - BRANCH=master
        - CMAKE_GENERATOR="Unix Makefiles"
    - <<: *robotologytddtemplate
      env:
        - DOCKER_BASE_IMAGE="ubuntu:bionic"
        - DOCKER_IMAGE_TAG="gazebo9master"
        - GAZEBO_VER=9
        - BRANCH=master
        - CMAKE_GENERATOR="Unix Makefiles"
        - IS_LATEST=true
    # -----
    # DEVEL
    # -----
    - <<: *robotologytddtemplate
      env:
        - DOCKER_BASE_IMAGE="ubuntu:xenial"
        - DOCKER_IMAGE_TAG="gazebo8devel"
        - GAZEBO_VER=8
        - BRANCH=devel
        - CMAKE_GENERATOR="Unix Makefiles"
    - <<: *robotologytddtemplate
      env:
        - DOCKER_BASE_IMAGE="ubuntu:bionic"
        - DOCKER_IMAGE_TAG="gazebo9devel"
        - GAZEBO_VER=9
        - BRANCH=devel
        - CMAKE_GENERATOR="Unix Makefiles"
